# fly.toml app configuration file generated for cactus-voice-reader on 2024-07-17T14:22:45+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cactus-voice-reader'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 5005
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/healthcheck'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
