# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: placeholder_default

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/

language: ko

pipeline:
  - name: "custom_components.custom_components.OktTokenizer"
  - name: "RegexFeaturizer"
  - name: "LexicalSyntacticFeaturizer"
  - name: "CountVectorsFeaturizer"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: "DIETClassifier"
    epochs: 200  # 에포크 수를 늘려 학습을 더 오래 진행
    hidden_layers_sizes: {"text": [256, 128]}  # 은닉층 크기 조정
    learning_rate: 0.001  # 학습률 조정
  - name: "EntitySynonymMapper"
  - name: "ResponseSelector"
  - name: "FallbackClassifier"
    threshold: 0.9
    ambiguity_threshold: 0.4

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 2
    epochs: 100
  - name: RulePolicy
    core_fallback_action_name: "action_default_fallback"
    core_fallback_threshold: 0.4
    enable_fallback_prediction: True